/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DAO.BookDAO;
import Data.MyOrder;
import Data.Order;
import static Form.CartForm.jTable1;
import Service.BookService;
import Service.DataTableRenderer;
import Service.OrderService;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import static com.mongodb.client.model.Filters.eq;
import com.sun.xml.internal.bind.v2.runtime.output.SAXOutput;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author Easy_IT
 */
public class MyOrderDetailForm extends javax.swing.JFrame {

    MyOrder myOrder;

    public MyOrderDetailForm(MyOrder order) {
        initComponents();
        myOrder = order;
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("OrderID");
        model.addColumn("Date");
        model.addColumn("Price");
        model.addColumn("Status");

        model.addRow(new Object[]{order.getOrderID(), order.getDate(), order.getPriceAll(), order.getStatus()});
        int orderId = Integer.parseInt(order.getOrderID());
        OrderView.setModel(model);
        OrderView.setRowHeight(25);

        ArrayList<Order> myorders = OrderService.showMyOrderDetail(orderId);

        DefaultTableModel model2 = new DefaultTableModel();
        model2.addColumn("ปก");
        model2.addColumn("ชื่อหนังสือ");
        model2.addColumn("ราคา");

        for (int i = 0; i < myorders.size(); i++) {
            model2.addRow(new Object[]{myorders.get(i).getBookCover(), myorders.get(i).getBookName(), myorders.get(i).getBookPrice()});

        }
        OrderViewDetail.setModel(model2);
        OrderViewDetail.getColumn("ปก").setCellRenderer(new BookService());
        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) OrderViewDetail.getDefaultRenderer(Object.class);
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        OrderViewDetail.setRowHeight(100);
        OrderViewDetail.getColumnModel().getColumn(0).setPreferredWidth(300);
        OrderViewDetail.getColumnModel().getColumn(1).setPreferredWidth(480);
        OrderViewDetail.getColumnModel().getColumn(2).setPreferredWidth(480);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OrderView = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        OrderViewDetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        OrderView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "OrderID", "Date", "Price", "Status"
            }
        ));
        OrderView.setRowHeight(25);
        jScrollPane1.setViewportView(OrderView);

        OrderViewDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ปก", "ชื่อหนังสือ", "ราคา"
            }
        ));
        OrderViewDetail.setRowHeight(75);
        jScrollPane2.setViewportView(OrderViewDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderView;
    private javax.swing.JTable OrderViewDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
